# Generated by Django 3.0.6 on 2020-07-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('aspect', models.CharField(blank=True, max_length=150)),
                ('packaging', models.CharField(blank=True, max_length=150)),
                ('size', models.CharField(blank=True, max_length=150)),
                ('caliber', models.CharField(blank=True, max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Concrete Product',
                'verbose_name_plural': 'Concrete Products',
            },
        ),
        migrations.AddConstraint(
            model_name='concreteproduct',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'variety', 'aspect', 'packaging', 'size', 'caliber'), name='concrete_product_unique'),
        ),
    ]
