# Generated by Django 3.0.6 on 2020-07-03 09:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concrete_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0.01, max_digits=22, validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier_observation', models.TextField(blank=True, max_length=150, verbose_name="supplier's observation")),
                ('date_start', models.DateField(blank=True, default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('date_end', models.DateField(blank=True, default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('valid', models.BooleanField(default=True)),
                ('concrete_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concrete_products.ConcreteProduct')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
