# Generated by Django 3.0.6 on 2020-06-05 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('varieties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, size=None)),
                ('aspects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, size=None)),
                ('packagings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, size=None)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, size=None)),
                ('calibers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_by_name'),
        ),
    ]
