# Generated by Django 3.0.6 on 2020-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('variety', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'variety'), name='product_unique'),
        ),
    ]
